# A Github action that uses codespell to check spell.
# .codespell/.codespellrc is a config file.
# .codespell/wordlist.txt is a list of words that will ignore word checks.
# More details please check the following link:
# https://github.com/codespell-project/codespell

name: Teku PeerDAS related tests

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle assemble
        run: ./gradlew --no-daemon --parallel clean :beacon:sync:test :data:provider:test :ethereum:spec:test :ethereum:statetransition:test :infrastructure:async:test :infrastructure:kzg:test :infrastructure:metrics:test :networking:eth2:test :networking:p2p:test